### ISSUE TITLE
why  my about page is not well?

### ISSUE THREAD

**Issue by LoveqLRC** [myJekyll/jasper2#20]
I am a newcomer to this.
This my [GitHub Pages](https://loveqlrc.github.io/).But [about page](https://loveqlrc.github.io/about/) is not well .This my [project](https://github.com/LoveqLRC/LoveqLRC.github.io),Could you tell me Where is the mistake

**Comment by LoveqLRC** [comment]
I solved it.thanks you for your job

**Comment by biomadeira** [comment]
@LoveqLRC glad you sorted it out... sorry I was offline for a couple of weeks...
